<?php

namespace Mautic\CoreBundle\Tests\Unit\Form\Type;

use Mautic\CoreBundle\Form\Type\SortableValueLabelListType;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class SortableValueLabelListTypeTest extends TestCase
{
    public function testBuildFormMakesValueOptional(): void
    {
        $builder = $this->createMock(FormBuilderInterface::class);
        $type    = new SortableValueLabelListType();

        $call = 0;
        $builder->expects($this->exactly(2))
            ->method('add')
            ->with($this->callback(function ($name) {
                $expected = [
                    ['label', 'value'],
                ];

                return in_array($name, $expected[0], true);
            }),
                $this->callback(function ($type) {
                    return TextType::class === $type;
                }),
                $this->callback(function ($options) use (&$call) {
                    $expectedOptions = [
                        [
                            'label'          => 'mautic.core.label',
                            'error_bubbling' => true,
                            'attr'           => ['class' => 'form-control'],
                        ],
                        [
                            'label'          => 'mautic.core.value_autogenerated',
                            'error_bubbling' => true,
                            'required'       => false,
                            'attr'           => ['class' => 'form-control'],
                        ],
                    ];
                    $result = $options === $expectedOptions[$call];
                    ++$call;

                    return $result;
                })
            );

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isType('callable'));

        $type->buildForm($builder, []);
    }

    public function testBuildViewSetsViewVariables(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createMock(FormInterface::class);
        $view = $this->createMock(FormView::class);

        $options = [
            'attr' => [
                'preaddon_attr'  => ['class' => 'test-preaddon'],
                'postaddon_attr' => ['class' => 'test-postaddon'],
                'preaddon'       => 'ri-test',
                'postaddon'      => 'ri-test-end',
            ],
        ];

        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals(['class' => 'test-preaddon'], $view->vars['preaddonAttr']);
        $this->assertEquals(['class' => 'test-postaddon'], $view->vars['postaddonAttr']);
        $this->assertEquals('ri-test', $view->vars['preaddon']);
        $this->assertEquals('ri-test-end', $view->vars['postaddon']);
    }

    public function testBuildViewWithEmptyOptions(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createMock(FormInterface::class);
        $view = $this->createMock(FormView::class);

        $options    = ['attr' => []];
        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals([], $view->vars['preaddonAttr']);
        $this->assertEquals([], $view->vars['postaddonAttr']);
        $this->assertEquals([], $view->vars['preaddon']);
        $this->assertEquals([], $view->vars['postaddon']);
    }

    public function testFormEventListenerWithNonArrayData(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isType('callable'));

        $type->buildForm($builder, []);
    }

    public function testFormEventListenerWithEmptyLabel(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isType('callable'));

        $type->buildForm($builder, []);
    }

    public function testFormEventListenerWithNonEmptyValue(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isType('callable'));

        $type->buildForm($builder, []);
    }

    public function testFormEventListenerAutoGeneratesValue(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $eventListener = null;
        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener) {
                $eventListener = $callback;

                return true;
            }));

        $type->buildForm($builder, []);

        $this->assertNotNull($eventListener, 'Event listener should be set');

        $event = $this->createMock(FormEvent::class);
        $data  = [
            'label' => 'Test Label',
            'value' => '',
        ];

        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        $event->expects($this->once())
            ->method('setData')
            ->with($this->callback(function ($newData) {
                return 'Test Label' === $newData['label'] && 'test_label' === $newData['value'];
            }));

        $eventListener($event);
    }

    public function testFormEventListenerDoesNotModifyWhenValueExists(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $eventListener = null;
        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener) {
                $eventListener = $callback;

                return true;
            }));

        $type->buildForm($builder, []);

        $this->assertNotNull($eventListener, 'Event listener should be set');

        $event = $this->createMock(FormEvent::class);
        $data  = [
            'label' => 'Test Label',
            'value' => 'existing_value',
        ];

        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        $event->expects($this->never())
            ->method('setData');

        $eventListener($event);
    }

    public function testFormEventListenerDoesNotModifyWhenLabelEmpty(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $eventListener = null;
        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener) {
                $eventListener = $callback;

                return true;
            }));

        $type->buildForm($builder, []);

        $this->assertNotNull($eventListener, 'Event listener should be set');

        $event = $this->createMock(FormEvent::class);
        $data  = [
            'label' => '',
            'value' => '',
        ];

        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        $event->expects($this->never())
            ->method('setData');

        $eventListener($event);
    }

    public function testFormEventListenerHandlesNonArrayData(): void
    {
        $type    = new SortableValueLabelListType();
        $builder = $this->createMock(FormBuilderInterface::class);

        $eventListener = null;
        $builder->expects($this->exactly(2))
            ->method('add');

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener) {
                $eventListener = $callback;

                return true;
            }));

        $type->buildForm($builder, []);

        $this->assertNotNull($eventListener, 'Event listener should be set');

        $event = $this->createMock(FormEvent::class);
        $data  = 'not_an_array';

        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        $event->expects($this->never())
            ->method('setData');

        $eventListener($event);
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('slugifyDataProvider')]
    public function testSlugifyMethod(string $input, string $expected): void
    {
        $type       = new SortableValueLabelListType();
        $reflection = new \ReflectionClass($type);
        $method     = $reflection->getMethod('slugify');
        $method->setAccessible(true);

        $result = $method->invoke($type, $input);
        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<int, array{string, string}>
     */
    public static function slugifyDataProvider(): array
    {
        /** @var array<int, array{string, string}> $data */
        $data = [
            ['My Option', 'my_option'],
            ['First Choice!', 'first_choice'],
            ['Test-Value_123', 'test_value_123'],
            ['Special@#$%Characters', 'special_characters'],
            ['  Trimmed  Spaces  ', 'trimmed_spaces'],
            ['Multiple___Underscores', 'multiple_underscores'],
            ['Àccénted Chàracters', 'accented_characters'],
            ['', ''],
            ['123Numbers', '123numbers'],
        ];

        return $data;
    }
}
